package com.hytalezx.ultimatebossfights.Utils;

import com.hypixel.hytale.server.core.HytaleServer;
import com.hypixel.hytale.server.core.universe.Universe;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.StringJoiner;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

public class HStats {

    private static final String URL_BASE = "https://api.hstats.dev/api/";

    /** Reads hstats_uuid from plugin.properties injected at build time. */
    public static String loadUUID() {
        try (InputStream in = HStats.class.getClassLoader().getResourceAsStream("plugin.properties")) {
            if (in == null) return null;
            Properties props = new Properties();
            props.load(in);
            String uuid = props.getProperty("hstats_uuid", "").trim();
            return uuid.isEmpty() || uuid.startsWith("MISSING") ? null : uuid;
        } catch (IOException e) {
            return null;
        }
    }

    private final String modUUID;
    private final String modVersion;
    private final String serverUUID;

    public HStats(String modUUID, String modVersion) {
        this.modUUID     = modUUID;
        this.modVersion  = modVersion;
        this.serverUUID  = getServerUUID();

        if (serverUUID == null) {
            System.out.println("[HStats] Metrics are disabled on this server.");
            return;
        }

        logMetrics();
        addModToServer();
        HytaleServer.SCHEDULED_EXECUTOR.scheduleAtFixedRate(this::logMetrics, 5, 5, TimeUnit.MINUTES);
    }

    public HStats(String modUUID) {
        this(modUUID, "Unknown");
    }

    private void logMetrics() {
        Map<String, String> data = new HashMap<>();
        data.put("server_uuid",    serverUUID);
        data.put("players_online", String.valueOf(getOnlinePlayerCount()));
        data.put("os_name",        System.getProperty("os.name"));
        data.put("os_version",     System.getProperty("os.version"));
        data.put("java_version",   System.getProperty("java.version"));
        data.put("cores",          String.valueOf(Runtime.getRuntime().availableProcessors()));
        sendRequest(URL_BASE + "server/update-server", data);
    }

    private void addModToServer() {
        System.out.println("[HStats] Adding mod to server metrics...");
        Map<String, String> data = new HashMap<>();
        data.put("server_uuid",    serverUUID);
        data.put("plugin_uuid",    modUUID);
        data.put("plugin_version", modVersion);
        sendRequest(URL_BASE + "server/add-plugin", data);
    }

    private String getServerUUID() {
        var path = Paths.get("hstats-server-uuid.txt");
        try {
            if (Files.exists(path)) {
                String content = Files.readString(path).trim();
                String[] lines = content.split("\n");
                if (lines.length < 5) return null;
                String enabled = lines[3].split("=")[1].trim();
                if (!enabled.equalsIgnoreCase("true")) return null;
                return lines[4];
            }
            String uuid = UUID.randomUUID().toString();
            Files.writeString(path,
                    "# HStats server metrics file\n" +
                    "# Do not edit this file manually.\n" +
                    "# To disable metrics set metrics_enabled=false\n" +
                    "metrics_enabled=true\n" +
                    uuid);
            return uuid;
        } catch (IOException e) {
            return null;
        }
    }

    private void sendRequest(String url, Map<String, String> params) {
        try {
            HttpURLConnection conn = (HttpURLConnection) URI.create(url).toURL().openConnection();
            conn.setRequestMethod("POST");
            conn.setDoOutput(true);
            conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");

            StringJoiner body = new StringJoiner("&");
            for (Map.Entry<String, String> e : params.entrySet()) {
                body.add(URLEncoder.encode(e.getKey(),   StandardCharsets.UTF_8) + "=" +
                         URLEncoder.encode(e.getValue(), StandardCharsets.UTF_8));
            }

            byte[] bytes = body.toString().getBytes(StandardCharsets.UTF_8);
            conn.setFixedLengthStreamingMode(bytes.length);
            try (OutputStream os = conn.getOutputStream()) {
                os.write(bytes);
            }

            int code = conn.getResponseCode();
            var stream = (code >= 200 && code < 300) ? conn.getInputStream() : conn.getErrorStream();
            if (stream != null) stream.readAllBytes();
            conn.disconnect();
        } catch (Exception ignored) {}
    }

    private int getOnlinePlayerCount() {
        return Universe.get().getPlayerCount();
    }
}
